rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
postgres:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_USER: "postgres"
  ports:
    - "5432:5432"